version: '3'
services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootPassword
      MYSQL_DATABASE: finx
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - ./db/:/var/lib/mysql
    ports:
      - '3306:3306'
