import './global.css';
import { ThemeProvider } from './theme-provider';
import Appbar from '@next-app/features/appBar';

export const metadata = {
  title: 'Welcome to next-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="de" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Appbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
